version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            python -m tests.unit_tests
      - run:
          name: deploy to heroku
          command: |
            git push https://heroku:5d9b0311-2ab0-41ed-ab3e-aaf05dd12237@git.heroku.com/ancient-bayou-70274.git master